// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnUMsTMXNVF3z49RIxRaMjOnOgOyGMKiU',
    appId: '1:919333673755:web:19a5acc50fbb52701051be',
    messagingSenderId: '919333673755',
    projectId: 'gokceada-688c7',
    authDomain: 'gokceada-688c7.firebaseapp.com',
    databaseURL: 'https://gokceada-688c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gokceada-688c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPFd-5utIlJQbFC7WcjuQpNNpttDvYEps',
    appId: '1:919333673755:android:556e785f5fae57dc1051be',
    messagingSenderId: '919333673755',
    projectId: 'gokceada-688c7',
    databaseURL: 'https://gokceada-688c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gokceada-688c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1fQt3RkUR3lMTuoCsq0KNQxyScsL09qQ',
    appId: '1:919333673755:ios:5abca3f1c4699a741051be',
    messagingSenderId: '919333673755',
    projectId: 'gokceada-688c7',
    databaseURL: 'https://gokceada-688c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gokceada-688c7.appspot.com',
    androidClientId: '919333673755-c3k5pndlb3jp2f4insmsrf0jq8nqjc3l.apps.googleusercontent.com',
    iosClientId: '919333673755-e8k9kc0a92rhinv8t606cra1i05ntaj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gokceada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1fQt3RkUR3lMTuoCsq0KNQxyScsL09qQ',
    appId: '1:919333673755:ios:5abca3f1c4699a741051be',
    messagingSenderId: '919333673755',
    projectId: 'gokceada-688c7',
    databaseURL: 'https://gokceada-688c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gokceada-688c7.appspot.com',
    androidClientId: '919333673755-c3k5pndlb3jp2f4insmsrf0jq8nqjc3l.apps.googleusercontent.com',
    iosClientId: '919333673755-e8k9kc0a92rhinv8t606cra1i05ntaj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gokceada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnUMsTMXNVF3z49RIxRaMjOnOgOyGMKiU',
    appId: '1:919333673755:web:82b20b11fe58ce841051be',
    messagingSenderId: '919333673755',
    projectId: 'gokceada-688c7',
    authDomain: 'gokceada-688c7.firebaseapp.com',
    databaseURL: 'https://gokceada-688c7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'gokceada-688c7.appspot.com',
  );
}
